---
title: "Assignment 1a (Python) - refactor obesity dataset code"
output: html_notebook
---

The below code downloads data from the obesity dataset from the [UC Irvine ML repository](https://doi.org/10.24432/C5H31Z). It then preprocesses the data, fits a machine-learning model and shows results. The coding style intentionally is not perfect.

```{r installing and loading packages}
library(httr)
library(readr)
library(ggplot2)
library(randomForest)
library(dplyr)
```

```{r functions}
source("functions.R")
```

```{r loading the data}
## Define the URL for the data
url <- 'https://archive.ics.uci.edu/static/public/544/estimation+of+obesity+levels+based+on+eating+habits+and+physical+condition.zip'

## Download the data from the URL
httr::GET(url, write_disk('obesity.zip', overwrite = TRUE)) |> stop_for_status()

unzip('obesity.zip', exdir = './data')

## Load the data
obesity <- readr::read_csv('data/ObesityDataSet_raw_and_data_sinthetic.csv', show_col_types = FALSE)
```

```{r renaming the variables}
## Renaming according to the tidyverse styleguide
obesity <-  obesity %>%
  rename(
    gender = Gender,
    age = Age,
    height = Height,
    weight = Weight,
    family_history_obesity = family_history_with_overweight,
    freq_highcal = FAVC,
    freq_veg = FCVC,
    main_meals = NCP,
    cons_between = CAEC,
    smoking_status = SMOKE,
    cons_water = CH2O,
    cal_monitoring = SCC,
    freq_phys_activity = FAF,
    time_tech_use = TUE,
    cons_alcohol = CALC,
    mode_transport = MTRANS,
    obesity_class = NObeyesdad
  )

```

```{r create and categorize BMI}
## Create the BMI variable
obesity$bmi <- obesity$weight / (obesity$height)^2

plot(obesity$bmi, type = 'l')

obesity <- obesity %>%
  mutate(
    label = case_when(
      bmi < 18.5 ~ "0_underweight",
      bmi < 25   ~ "1_normal",
      bmi < 30   ~ "2_overweight",
      TRUE       ~ "3_obese"
    )
  )


```

```{r split the data}
## Split the data for the web part and the synthetic part
## Do this after creating the BMI variable
obesity_web <- obesity[1:498, ]
obesity_synthetic <- obesity[499:nrow(obesity), ]

```

```{r converting variables to numeric}

## Make the mode of transport variable binary
obesity_web <- obesity_web %>%
  mutate(
    mode_transport = if_else(
      mode_transport %in% c("Walking", "Bike"),
      1L,
      0L
    )
  )

obesity_web$mode_transport <- as.numeric(obesity_web$mode_transport)

## Make the gender variable numeric
obesity_web$gender <- ifelse(obesity_web$gender == "Male", 1L, 0L)

obesity_web$gender <- as.numeric(obesity_web$gender)

## Convert the binary variables
obesity_web$family_history_obesity <- convert_binary(obesity_web$family_history_obesity)
obesity_web$freq_highcal <- convert_binary(obesity_web$freq_highcal)
obesity_web$smoking_status <- convert_binary(obesity_web$smoking_status)
obesity_web$cal_monitoring <- convert_binary(obesity_web$cal_monitoring)

## Converting the ordinal variables to numeric
obesity_web$cons_between <- convert_ordinal(obesity_web$cons_between)
obesity_web$cons_alcohol <- convert_ordinal(obesity_web$cons_alcohol)
```

## Regression problem

```{r calculating class weights}
## Storing the prevalence of the classes
freq <- table(obesity_web$label)

## Calculating the class weight
class_weight <- length(obesity_web$label) / (length(unique(obesity_web$label)) * as.numeric(freq))

## Assigning names to the weights
names(class_weight) <- names(freq)

print(class_weight)
```

```{r split train and test set}
# Note: result can deviate from the python code due to random seed!
set.seed(42)

## Create an index variable
index <- seq_len(nrow(obesity_web))

# Create train and test datasets
## Make the indices for the train and test dataset
index_train <- sample(index, size = floor(0.7 * length(index)))
index_test <- setdiff(index, index_train)

## Create the actual datasets
obesity_train <- obesity_web[index_train,]
obesity_test <- obesity_web[index_test,]

## Create a train and test set for the bmi variable
bmi_train <- obesity_web$bmi[index_train]
bmi_test <- obesity_web$bmi[index_test]

## Assign the weight to the train dataset
obesity_train_weighted <- class_weight[obesity_web$label[index_train]]
```

```{r model specifying}
## Making the linear model
linear_mod <- lm(bmi ~ ., data = obesity_train)

## Making a random forest model
random_forest_mod <- randomForest(x = obesity_train, y = bmi_train, ntree = 100, nodesize = 5, maxnodes = 20)
```

```{r predict the models}
## Predict based on the regression
preds_linear_mod <- predict(linear_mod, obesity_test)

## Predict based on the random forest
preds_random_forest_mod <- predict(random_forest_mod, obesity_test)
```

```{r plot the models}
## plot the predictions for bmi with the linear regression model
plot(preds_linear_mod, bmi_test,
     pch = 16,
     col = rgb(0, 0, 0, 0.5))
abline(a = 0, b = 1, col = "red", lty = 3)

## plot the predictions for bmi with the random forest model
plot(preds_random_forest_mod, bmi_test,
     pch = 16,
     col = rgb(0, 0, 0, 0.5))
abline(0, 1, col = "red", lty = 3)
```

```{r test the Mean Absolute Error}
## Create weights for the test set
sample_weights_test <- class_weight[obesity_test$label]

## Predict the Mean Absolute Error when predicting the mean
mae_baseline <- sum(abs(bmi_test - rep(mean(bmi_train), length(bmi_test))) * sample_weights_test) / sum(sample_weights_test)

## Predicht the actual Mean Absolute Error with the mean
mae_model <- sum(abs(bmi_test - preds_linear_mod) * sample_weights_test) /
             sum(sample_weights_test)

## Print the Mean Absolute Error of the models
cat(sprintf('Mean absolute error (baseline): %.3f\n', mae_baseline))
cat(sprintf('Mean absolute error: %.3f\n', mae_model))
```
